package kb

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ajramos/giznews/internal/db"
)

// vaultOrigin marks a note row as read from a file the user wrote. Rows without
// it were generated by giznews, which owns their content even when the reader
// has since edited the file — that case belongs to Vault.Sync, not here.
const vaultOrigin = `{"origin":"vault"}`

// ImportResult reports what a vault scan took in.
type ImportResult struct {
	Imported int `json:"imported"`
	Updated  int `json:"updated"`
	Mentions int `json:"mentions"`
	Skipped  int `json:"skipped"`
}

var wikilinkRe = regexp.MustCompile(`\[\[([^\]|#]+)`)

// SyncVault reads the notes the user wrote by hand into the graph. Until now
// the vault only received: a note typed in Obsidian was invisible to search, to
// the graph and to the concept counts, however many times it cited them.
//
// Only files giznews does not own are considered — a generated note carries its
// markers, a generated view says so in its frontmatter — and none of them is
// ever written back. The user's file stays the source of truth; the database
// keeps a copy and the fingerprint that says whether it changed since.
func (s *Service) SyncVault(ctx context.Context) (*ImportResult, error) {
	res := &ImportResult{}
	kbRepo := db.NewKBRepo(s.db)
	conceptRepo := db.NewConceptRepo(s.db)

	err := filepath.WalkDir(s.vault.Root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(strings.ToLower(d.Name()), ".md") {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			if s.logger != nil {
				s.logger.Printf("kb: cannot read %s: %v", path, err)
			}
			res.Skipped++
			return nil
		}
		content := string(raw)
		if strings.Contains(content, markerBegin) || isGeneratedView(content) {
			return nil // giznews wrote this one
		}

		note, outcome, err := s.importNote(ctx, kbRepo, path, content, hashOf(raw))
		if err != nil {
			return err
		}
		switch outcome {
		case importSkipped:
			res.Skipped++
			return nil
		case importCreated:
			res.Imported++
		case importUpdated:
			res.Updated++
		}

		mentions, err := s.recordUserMentions(ctx, conceptRepo, note)
		if err != nil {
			return err
		}
		res.Mentions += mentions
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("kb: scan vault: %w", err)
	}
	if s.logger != nil && (res.Imported > 0 || res.Updated > 0) {
		s.logger.Printf("kb sync: %d note(s) imported, %d updated, %d concept mention(s)",
			res.Imported, res.Updated, res.Mentions)
	}
	return res, nil
}

type importOutcome int

const (
	importSkipped importOutcome = iota
	importCreated
	importUpdated
)

// importNote mirrors one hand-written file into kb_notes, creating the row on
// first sight and refreshing it when the file changed.
func (s *Service) importNote(ctx context.Context, repo *db.KBRepo, path, content, hash string) (*db.KBNote, importOutcome, error) {
	existing, err := repo.GetByPath(ctx, path)
	if err != nil && !errors.Is(err, db.ErrNotFound) {
		return nil, importSkipped, err
	}

	links := parseWikilinks(content)
	tags := parseTags(content)
	title := parseTitle(content, path)
	noteType := noteTypeFor(path, content)

	if existing != nil {
		if existing.ContentHash == hash || existing.Frontmatter != vaultOrigin {
			// Either nothing changed, or this is a giznews note whose file the
			// reader rewrote: taking over the row here would silently stop the
			// note from ever tracking its article again.
			return existing, importSkipped, nil
		}
		existing.Title = title
		existing.Content = content
		existing.Tags = tags
		existing.Wikilinks = links
		if err := repo.Update(ctx, existing); err != nil {
			return nil, importSkipped, err
		}
		if err := repo.SetContentHash(ctx, existing.ID, hash); err != nil {
			return nil, importSkipped, err
		}
		existing.ContentHash = hash
		return existing, importUpdated, nil
	}

	base := Slugify(strings.TrimSuffix(filepath.Base(path), filepath.Ext(path)))
	slug := s.uniqueSlug(ctx, repo, base, nil)
	if slug != base && s.logger != nil {
		s.logger.Printf("kb: %s imported as %q, its own name was taken", path, slug)
	}
	note, err := repo.Create(ctx, db.NewKBNote{
		Type: noteType, Title: title, Slug: slug, Path: path,
		Frontmatter: vaultOrigin, Content: content, Tags: tags, Wikilinks: links,
		ContentHash: hash,
	})
	if err != nil {
		return nil, importSkipped, fmt.Errorf("kb: import %s: %w", path, err)
	}
	return note, importCreated, nil
}

// recordUserMentions counts a hand-written note's links to concepts that already
// exist. Links to anything else are ordinary note links: a reader referencing an
// atom is not naming a new concept, and inventing one from every wikilink would
// fill the promotion queue with noise.
func (s *Service) recordUserMentions(ctx context.Context, repo *db.ConceptRepo, note *db.KBNote) (int, error) {
	n := 0
	for _, link := range note.Wikilinks {
		slug, err := repo.Resolve(ctx, link)
		if err != nil {
			return n, err
		}
		concept, err := repo.Get(ctx, slug)
		if errors.Is(err, db.ErrNotFound) {
			continue
		}
		if err != nil {
			return n, err
		}
		if _, err := repo.Touch(ctx, concept.Slug, concept.Name, note.ID); err != nil {
			return n, err
		}
		n++
	}
	return n, nil
}

// isGeneratedView reports whether a file is one of the maps giznews rewrites on
// every build (the index, the promotion queue, the day's note).
func isGeneratedView(content string) bool {
	fm, _ := splitFrontmatter(content)
	return strings.Contains(fm, "\nstatus: generated\n")
}

func parseWikilinks(content string) []string {
	var out []string
	for _, m := range wikilinkRe.FindAllStringSubmatch(content, -1) {
		slug := strings.TrimSpace(m[1])
		if slug == "" {
			continue
		}
		out = appendUnique(out, slug)
	}
	return out
}

func parseTags(content string) []string {
	fm, _ := splitFrontmatter(content)
	if fm == "" {
		return nil
	}
	blocks, _ := frontmatterBlocks(fm)
	var out []string
	for _, line := range blocks["tags"] {
		item, ok := strings.CutPrefix(strings.TrimRight(line, "\n"), "  - ")
		if !ok {
			continue
		}
		if tag := unquoteYAML(strings.TrimSpace(item)); tag != "" {
			out = appendUnique(out, tag)
		}
	}
	return out
}

// parseTitle prefers the note's first heading, then its frontmatter title, and
// falls back to the file name.
func parseTitle(content, path string) string {
	_, body := splitFrontmatter(content)
	for _, line := range strings.Split(body, "\n") {
		if heading, ok := strings.CutPrefix(strings.TrimSpace(line), "# "); ok {
			if t := strings.TrimSpace(heading); t != "" {
				return t
			}
		}
	}
	fm, _ := splitFrontmatter(content)
	if fm != "" {
		blocks, _ := frontmatterBlocks(fm)
		if lines := blocks["title"]; len(lines) > 0 {
			if _, value, ok := strings.Cut(strings.TrimRight(lines[0], "\n"), ":"); ok {
				if t := unquoteYAML(strings.TrimSpace(value)); t != "" {
					return t
				}
			}
		}
	}
	return strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
}

// noteTypeFor takes the type the note declares, falling back to the folder it
// was filed in.
func noteTypeFor(path, content string) db.NoteType {
	declared := ""
	if fm, _ := splitFrontmatter(content); fm != "" {
		blocks, _ := frontmatterBlocks(fm)
		if lines := blocks["type"]; len(lines) > 0 {
			if _, value, ok := strings.Cut(strings.TrimRight(lines[0], "\n"), ":"); ok {
				declared = unquoteYAML(strings.TrimSpace(value))
			}
		}
	}
	byFolder := ""
	switch filepath.Base(filepath.Dir(path)) {
	case "01-Electrons":
		byFolder = "electron"
	case "02-Atoms":
		byFolder = "atom"
	case "03-Molecules":
		byFolder = "molecule"
	}
	for _, candidate := range []string{declared, byFolder} {
		switch db.NoteType(candidate) {
		case db.NoteAtom, db.NoteElectron, db.NoteMolecule, db.NoteInbox:
			return db.NoteType(candidate)
		}
	}
	return db.NoteInbox
}
